name: liveness_detector_sdk
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^10.2.0
  vibration: ^1.7.3
  image: ^4.0.17
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aniketproduction.liveness_detector_sdk
        pluginClass: LivenessDetectorSdkPlugin
      ios:
        pluginClass: LivenessDetectorSdkPlugin

  assets:
    - assets/animations/